import type { Metadata } from "next";
import { silka, myriadProCondensed } from "./fonts";
import Announcement from "@/components/Announcement";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${silka.variable} ${myriadProCondensed.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Announcement
          text="Free Shipping on all orders over $50"
          bgColor="#000d8c"
          textColor="#ffffff"
        />
        <Header />
        {children}
      </body>
    </html>
  );
}
